OPTIONS (SKIP=1)
LOAD DATA
INFILE "DATA/DATA_DEUDACLIENTE.txt"
TRUNCATE PRESERVE BLANKS
INTO TABLE TMP_DEUDACLIENTE
fields terminated by '"	"'
trailing nullcols
(
CODMES			,
TIPREGISTRO		,
CODSBSCLIENTE	,
CODENTIDAD		,
TIPCREDITO		,
CODCUENTA		,
DIASATRASO		,
SALDO			,
CLASIFICACION	
)
