OPTIONS (SKIP=1)
LOAD DATA
INFILE "DATA/DATA_UBIGEO.txt"
TRUNCATE PRESERVE BLANKS
INTO TABLE TMP_UBIGEO
fields terminated by '	'
trailing nullcols
(
UBIGEO				,
DEPARTAMENTO 		,
PROVINCIA			,
DISTRITO			,
CODIGO	        	,
DISTRITODET		,
FLGZONA				,
CENTROSNEGOCIO  	,
FLGPROVCENTROSNEGOCIO ,
DISTRITOAGG    ,
FLGCIUDAD		
)
