OPTIONS (SKIP=1)
LOAD DATA
INFILE "DATA/DATA_ENTIDADESFINANCIERAS.txt"
TRUNCATE PRESERVE BLANKS
INTO TABLE TMP_ENTIDADFINANCIERA
fields terminated by '	'
trailing nullcols
(
CODENTIDAD			,
BANCO				,
BANCONOMCORTO		,
TIPENTIDAD			,
TIPCOMPETENCIA1		,
TIPCOMPETENCIA2		
)
