SET ECHO ON
SET TIMING ON
SET FEEDBACK ON

SPOOL &1;

--============================================
-- 		ESPECIALIZACION BI & BIG DATA
--============================================

-- CARGA DE TABLA DIM_ENTIDAD_FINANCIERA

TRUNCATE TABLE DIM_ENTIDAD_FINANCIERA;

INSERT INTO DIM_ENTIDAD_FINANCIERA
(
CODENTIDAD,
BANCO,
BANCONOMCORTO,
TIPENTIDAD,
TIPCOMPETENCIA1,
TIPCOMPETENCIA2,
FECCARGATABLA
)
SELECT 
	CODENTIDAD,
    BANCO,
    BANCONOMCORTO,
    TIPENTIDAD,
    TIPCOMPETENCIA1,
    TIPCOMPETENCIA2,				
	SYSDATE
FROM MA_ENTIDADFINANCIERA;

COMMIT;

DISCONNECT;
EXIT;
